### ISSUE TITLE
Question about Avgsend option in the simulation

### ISSUE THREAD

**Issue by spiroskatsampiris** [kqorany/FREE#1]

**Comment by spiroskatsampiris** [comment]
Hi, i would like to ask what actually is the avg send time. Is the time that each node transmits? if yes, this means that the node waits for avgsend sec then transmits for airtime sec. and then waits another avgsend sec. etc? I'd like to provide more features to the nodes such as operation states with different energy consumption.

**Comment by kqorany** [comment]
Sorry for the late response.

The sending times are following a poison distribution and lambda is the avgsend so on average, the process will be as you described.
