### ISSUE TITLE
Running Problem!

### ISSUE THREAD

**Issue by Benyaminteymuri** [kqorany/FREE#2]
Hi,
I was trying to run U're coding simulation and regenerating the result,
But when I running the "python LoRaWAN.py" I have a problem like this:

" File ".\LoRaWAN.py", line 112
    print "too long:", len(packetsAtBS)
          ^
SyntaxError: invalid syntax"

I was trying with every parameter, But I can run the module
And I have no idea where I made a mistake exactly!
Can help me to run this, please!

Thank U for supporting

**Comment by tetrodoxin** [comment]
Hi Ben,
I'm sorry to ask, but did you ensure, that your Environment runs the script with python 2.7?
This error is regularly reported by python 3, running incompatible python 2 scripts.

**Comment by Benyaminteymuri** [comment]
Hi
first of all thanks for u're response
and then, Yes! after running the script with python 2.7 it's totally work!
again thank U so much
